[colors]
[colors.primary]
background = "#040305"
foreground = "#d9d3de"

[colors.normal]
black   = "#040305"
red     = "#dc7070"
green   = "#70dc70"
yellow  = "#dcdc70"
blue    = "#7070dc"
magenta = "#dc70dc"
cyan    = "#70dcdc"
white   = "#ccc7d1"

[colors.bright]
black   = "#a694b8"
red     = "#ebadad"
green   = "#adebad"
yellow  = "#ebebad"
blue    = "#adadeb"
magenta = "#ebadeb"
cyan    = "#adebeb"
white   = "#d9d3de"

[colors.cursor]
text   = "#040305"
cursor = "#d9d3de"
