# Background and foreground colors
background = #040305
foreground = #d9d3de

# Standard colors
palette = 0=#040305
palette = 1=#dc7070
palette = 2=#70dc70
palette = 3=#dcdc70
palette = 4=#7070dc
palette = 5=#dc70dc
palette = 6=#70dcdc
palette = 7=#ccc7d1

# Bright colors
palette = 8=#a694b8
palette = 9=#ebadad
palette = 10=#adebad
palette = 11=#ebebad
palette = 12=#adadeb
palette = 13=#ebadeb
palette = 14=#adebeb
palette = 15=#d9d3de
