# Spectral Violet Hyprland Configuration
# Name: Spectral Violet
# Author: shmall03
# Description: Custom Hyprland settings for Spectral Violet.

# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(a970dcdc) rgba(00000070) rgba(a970dcdc) rgba(a970dcdc) rgba(00000070) rgba(a970dcdc) 45deg
}

misc {
    background_color = rgb(040305)
}

group {
    col.border_active = rgba(a970dcdc) rgba(00000070) rgba(a970dcdc) rgba(a970dcdc) rgba(00000070) rgba(a970dcdc) 45deg
}

decoration {
    active_opacity = 0.8627450980
    inactive_opacity = 0.431372549
    fullscreen_opacity = 1
    dim_special = 0

    blur {
        enabled = true
        new_optimizations = true
        special = true
        popups = true

        size = 2
        passes = 2
        contrast = 0.8627450980
        brightness = 0.431372549
    } 
}

animations {
    enabled = true
    bezier = smoothAll, 0, 0.2, 0.8, 1
    bezier = smoothIn, 0.2, 1, 0.4, 1
    bezier = smoothOut, 0.4, 0, 0.8, -0.6
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = softSnap, 0.4, 0, 0.2, 1

    animation = workspaces, 1, 8.31352549, overshot, slidefade
    animation = specialWorkspace, 1, 8.31352549, overshot, slidefadevert

    animation = windows, 1, 6.31352549, overshot, slide
    animation = windowsIn, 1, 6.31352549, overshot, slide
    animation = windowsOut, 1, 6.31352549, smoothOut, slide
    animation = windowsMove, 1, 4.31352549, softSnap
    
    animation = layersIn, 1, 8.31352549, smoothIn, slide down
    animation = layersOut, 1, 8.31352549, softSnap, slide down
    
    animation = fade, 1, 8.31352549, smoothIn
    animation = fadeOut, 1, 8.31352549, smoothOut
    animation = fadeSwitch, 1, 8.31352549, smoothIn
    animation = fadeShadow, 1, 8.31352549, smoothIn
    animation = fadeDim, 1, 8.31352549, smoothIn
    animation = fadeDpms, 1, 8.31352549, smoothIn
    animation = fadeLayers, 1, 8.31352549, softSnap
    
    animation = borderangle, 1, 215.6762745, linear, loop
}
