background            #040305
foreground            #d9d3de

# black
color0  #040305
color8  #a694b8

# red
color1  #dc7070
color9  #ebadad

# green
color2  #70dc70
color10 #adebad

# yellow
color3  #dcdc70
color11 #ebebad

# blue
color4  #7070dc
color12 #adadeb

# magenta
color5  #dc70dc
color13 #ebadeb

#cyan
color6  #70dcdc
color14 #adebeb

#white
color7  #ccc7d1
color15 #d9d3de


